# Generated by Django 4.2.20 on 2025-07-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_text',
            field=models.TextField(blank=True, help_text='Extracted text content of the file', null=True),
        ),
    ]
